### ISSUE TITLE
你好，我问一下怎么在一个文件中指定所有页面编译时需要的数据？

### ISSUE THREAD

**Issue by zhaojinzhao** [rpdg/fis3-parser-art-template4#1]
你好，我问一下怎么在一个文件中指定所有页面编译时需要的数据？
我在fis-conf.js配置文件中，这样指定不生效。是我配置错误还是其它原因？
谢谢您的回复。
![image](https://user-images.githubusercontent.com/6450511/33796087-b8bac082-dd28-11e7-9f8b-503b831ea444.png)

**Comment by rpdg** [comment]
![20171210123858](https://user-images.githubusercontent.com/1169162/33802097-631251fe-ddaa-11e7-875f-8f8fd5d1b23d.png)





有两个需要比较注意的地方，见图。一个是要match到子目录下的文件，一个是数据按照目录结构来，目录以'/'结尾，像你的结构就类似
 ```javascript
define:{
    pageTitle:"aaa",
    "index-form.html":{
        pageTitle: "bbb"
    }
}

**Comment by zhaojinzhao** [comment]
非常感谢，我的问题以解决。
