### ISSUE TITLE
如何提出 define字段？

### ISSUE THREAD

**Issue by J-env** [rpdg/fis3-parser-art-template4#2]
您好！
define 字段要是全在 fis-conf.js 中写那这个文件就特别长了，
该怎么提出来呢？
谢谢！

**Comment by rpdg** [comment]
为了让模版文件和数据分离，本插件对art-template的数据收集进行了三种形式的存放。

同目录下同名的json文件，即test.json对应为test.html的数据；
工程目录下的config.json，该数据为全局配置；
fis-config中插件的define字段。
