### ISSUE TITLE
新建一个layout.art文件，引用的页面路径无法处理

### ISSUE THREAD

**Issue by xiangcaozhu** [rpdg/fis3-parser-art-template4#4]
1、layout.art文件，里面使用相对路径引用和很多css、js路径；
2、在artcale.html中引用，layout.art布局，同时编写article.html自己的东西
3、fis3处理后，成功生成应用layout.art结构的完整的article.html的html5文档
问题：由于是layout.art里面引用相对路径，不同层级的html页面应用layout.art的时候，里面的相对路径无效，因此fis3无法资源定位。请问这个要怎么处理？能否在应用layou.art之前，先处理layout.art自己的路径，然后再应用到新的html页面中去？

**Comment by rpdg** [comment]
layout里可以用绝对路径么
